


#·þÎñ¶Ë¿Ú
server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://106.13.107.8:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: xiapenqiang
    password: xia952621
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 50
      min-idle: 1
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 300000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 6000
      max-evictable-idle-time-millis: 6000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  devtools:
    add-properties: true
logging:
  level:
    web: DEBUG
  file: D:\\my.log


